### ISSUE TITLE
Versions above 1.6.2 do not issue correct certificates

### ISSUE THREAD

**Issue by passcod** [passcod/certainly#4]
1.7 and higher swapped the openssl for a pure-rust solution. Somewhere in that conversion I made at least one mistake and certificates generated are missing _something_ but I haven't quite been able to identify _what_.

The short of it is, use 1.6.2:

```
cargo install certainly --version 1.6.2
```

If you have some time and motivation, and/or if you have some medium-deep knowledge of TLS certificates, you can help by figuring out what's missing.

**Comment by passcod** [comment]
This might have been related, need to re-test! https://github.com/est31/rcgen/issues/30

**Comment by dequis** [comment]
How do you reproduce this? Is it something as obvious as make self signed cert, put it in web server, connect web client to it?

**Comment by passcod** [comment]
Pretty much. Also with ca-signed certs. Also comparing the outputs of `openssl x509 -text -in cert.pem`.

**Comment by passcod** [comment]
Deprecating and archiving this repo.
