### ISSUE TITLE
Switch to searchable name

### ISSUE THREAD

**Issue by mleonhard** [passcod/certainly#5]
This project does not appear on the first page when searching for it on various search engines.  These searches fail:
- "rust certainly", [DDG](https://duckduckgo.com/?q=rust+certainly), [Bing](https://www.bing.com/search?q=rust+certainly), [Yahoo](https://search.yahoo.com/search?p=rust+certainly), [Baidu](https://www.baidu.com/s?wd=rust+certainly), [Yandex](https://yandex.ru/search/?text=rust%20certainly)
- "rust certainly certificate", [DDG](https://duckduckgo.com/?q=rust+certainly+certificate), [Bing](https://www.bing.com/search?q=rust+certainly+certificate), [Yahoo](https://search.yahoo.com/search?p=rust+certainly+certificate), [Baidu](https://www.baidu.com/s?wd=rust+certainly+certificate)

These succeed:
- "rust certainly", [Google](https://www.google.com/search?q=rust+certainly)
- "rust certainly certificate", [Google](https://www.google.com/search?q=rust+certainly+certificate), [Yandex](https://yandex.ru/search/?text=rust%20certainly%20certificate)

Please consider renaming the project.

Ideas for new names:
- certicus
- certruse
- certacles
- rustcertgen
- gencert
- certificand
- certifican
- certifigen
- certigen
- certgen
- certmaker42
- gimmecert
- tsukucert
- shincert
- zuocert
- certwriter
- certauthor
- certmeup
- certup
- yescert
- certyescert
- certy
- certlicious
- eggcert
- certlayer
- certan
- certski

**Comment by passcod** [comment]
no
